import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import './globals.css'
import SideNav from '@/components/navbar/sideNav'

const font = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Dashboard Generated by Yeong Meng',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
          <SideNav/>
          {children}
          <script src="../node_modules/flowbite/dist/flowbite.min.js"></script>
      </body>
    </html>
  )
}
