import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import './globals.css'
import SideNav from '@/components/navbar/sideNav'
import TopNav from '@/components/navbar/topNav'

const font = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Dashboard Generated by Yeong Meng',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} flex flex-col`}>
          <TopNav/>
          <div>
            <SideNav/>
            {children}
          </div>
          <script src="../node_modules/flowbite/dist/flowbite.min.js"></script>
      </body>
    </html>
  )
}
